### ISSUE TITLE
GDPR violation, data disclosure to Facebook and Google

### ISSUE THREAD

**Issue by alvar-freude** [ONLYOFFICE/documents-app-android#202]
According to this [report from Exodus Privacy](https://reports.exodus-privacy.eu.org/de/reports/com.onlyoffice.documents/latest/) the ONLYOFFICE Documents app for Android includes **tracking libraries from Facebook and Google.**
Disclosure of personal data to Google or Facebook needs a legal basis (Art. 6 GDPR). 

Under German and European law, the storage of information in the end user's device or access to information already stored in the device is only permissible if the end user has consented on the basis of clear and comprehensive information or if this is absolutely necessary in order to be able to provide a service expressly requested by the user (cf. § 25 TTDSG)

For more details see this [Tracking FAQ](https://www.baden-wuerttemberg.datenschutz.de/faq-zu-cookies-und-tracking-2/) of the Data protection supervisory authority of Baden-Württemberg, Germany (sorry, it is in German, you may use a translation service).

Since complying with all the requirements of proper consent for snitching to Google, Facebook and others is very difficult (see sections B and C of the [mentioned FAQ](https://www.baden-wuerttemberg.datenschutz.de/faq-zu-cookies-und-tracking-2/)), it is highly recommended to refrain from all processing that requires consent. This is especially true for privacy-friendly services like ONLYOFFICE.

**Therefore: the app should never transfer even a single bit of data anywhere unless the user has explicitly requested it.**

**Comment by alvar-freude** [comment]
The same applies to the iOS App, https://github.com/ONLYOFFICE/documents-app-ios, where it is not possible to open issues on Github.

**Comment by ayuzhin** [comment]
ONLYOFFICE mobile applications on Android and iOS use Facebook and Google services as one of the possible authorization methods on ONLYOFFICE portals, provided that the portal provides such an opportunity. All necessary permissions and user confirmation for the use of personal data are requested through the official SDKs provided by these services, immediately before their use in these services. The management of the personal data provided is possible through these services. The source code of our mobile applications is open and you can see for yourself how the SDK of these services is used.

**Comment by johans3** [comment]
Users appreciate Onlyoffice because IT IS a valid alternative to common corporation spyware. 
Similar to proprietary software, also Onlyoffice runs on all mayor platforms and users *expect* that Onlyoffice IS an alternative to commercial office spyware. it's not just about service and features but privacy - office data is important and vulnerable and not just some dumb grocery list - even worse if such documents are shared for collaboration 

Any excuse to integrate Facebook or Google is  fundamentally unacceptable. Even worse, users  aren't given an opportunity to opt out from these services. 

My guess is, Onlyoffice needs some authority for online collaboration. This is ok, but you need to find another possible authority and to keep these services disabled asking users explicitly and clearly for their consent prior to activate anything  sneaky running in the background

Most users won't know about these sneaky background services and they can't opt out from these "features" to exercise  their right, not even to mention, most people are unable to read code even if code is accessible, eg open source. Also they probably don't know about GitHub and have little time for digging like this. 
Finally, these trackers need replacement or need to be removed
You should publish a tracker-free (spyware-free) version on f-droid or drop features that harm users right,  privacy and safety

**Comment by postcanonical** [comment]
tracker free version for f-droid would be nice

**Comment by Andrew-Dudov** [comment]
This functionality is required by a large number of clients.
We will not delete trackers.

But we provide the opportunity to build our application without using these components by forking the repository and independently making changes to the code of the software product, acting within the framework of the license agreement. For this please contact sales@onlyoffice.com

**Comment by postcanonical** [comment]
> But we provide the opportunity to build our application without using these components by forking the repository and independently making changes to the code of the software product, acting within the framework of the license agreement. 

Only if it was possible. https://github.com/ONLYOFFICE/documents-app-android/issues/32#issuecomment-831988663 Says that it is not possible to compile without some closed sourced libs.

**Comment by jason-eu** [comment]
They knew exactly what they were saying when they made that response, the goal wasn't to help but to distract while obfuscating a pathway to a viable solution.
